version: '3.8'

services:
  tutoring_db:
    image: postgres:15
    container_name: tutoring_db
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: tutoring_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment: 
      WEBHOOK_TUNNEL_URL: 'http://n8n:5678/' 
    volumes:
      - n8n_data:/home/node/.n8nm
    restart: always
    networks:
      - app-network

  backend:
    build: .
    container_name: espaco_construir_backend
    environment:
      DB_URL: jdbc:postgresql://tutoring_db:5432/tutoring_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 8081
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
      ALLOWED_ORIGINS: http://localhost:5173
      N8N_WEBHOOK_URL: http://n8n:5678/webhook/Event
      N8N_WEBHOOK_CANCELATION_LESSON: http://n8n:5678/webhook/cancel-lesson
      N8N_WEBHOOK_PRODUCTION_URL: 
    ports:
      - "8081:8081"
    depends_on:
      - tutoring_db
      - n8n
    restart: unless-stopped
    networks:
      - app-network
      - evolution-net

networks:
  app-network:
    driver: bridge
  evolution-net:
    external: true

volumes:
  postgres_data:
  n8n_data: