version: '3.8'

services:
  tutoring_db:
    image: postgres:15
    container_name: tutoring_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment: 
      WEBHOOK_TUNNEL_URL: 'http://n8n:5678/' 
    volumes:
      - n8n_data:/home/node/.n8nm
    restart: always
    networks:
      - app-network

  backend:
    image: devadrianoo/instituto-desenvolver-backend:latest
    # build: .
    container_name: espaco_construir_backend
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - tutoring_db
      - n8n
    restart: unless-stopped
    networks:
      - app-network
      - evolution-net

networks:
  app-network:
    driver: bridge
  evolution-net:
    external: true

volumes:
  postgres_data:
  n8n_data: