spring:
  profiles:
    active: dev
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${USERNAME}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
app:
  frontend-url: ${FRONTEND_URL:http://localhost:5173}

server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

cors:
  allowed-origins: ${ALLOWED_ORIGINS:https://app.desenvolverinstituto.com,https://n8n.desenvolverinstituto.com,/evo.desenvolverinstituto.com,http://localhost:5173}

n8n:
  webhook-url-new-lesson: ${N8N_WEBHOOK_URL}
  webhook-url-cancelation-lesson: ${N8N_WEBHOOK_CANCELATION_LESSON:http://localhost:5678/webhook/cancel-lesson}

logging:
  level:
    org.springframework.security: DEBUG