spring:
  application:
    name: espaco-construir-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/tutoring_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
    validate-on-migrate: false
    clean-disabled: false
    clean-on-validation-error: true
    out-of-order: true
    ignore-missing-migrations: true
    ignore-future-migrations: true
