ALTER TABLE schedules 
ADD COLUMN IF NOT EXISTS description VARCHAR(255),
ADD COLUMN IF NOT EXISTS meeting_link VARCHAR(255),
ADD COLUMN IF NOT EXISTS subject VARCHAR(255) NOT NULL DEFAULT 'GENERAL'; 